openapi: 3.0.0
info:
  title: GitHub Search Repositories (Simplified)
  version: 1.0.0
  description: >
    Simplified schema for GitHub's /search/repositories endpoint.
    Only required fields for client display are included.

servers:
  - url: https://api.github.com

paths:
  /search/repositories:
    get:
      summary: Search repositories
      parameters:
        - name: q
          in: query
          required: true
          schema:
            type: string
          description: Query string, e.g. 'created:>2025-01-01 language:TypeScript'
        - name: sort
          in: query
          required: false
          schema:
            type: string
            enum: [stars]
          description: Sort field. Use 'stars' to sort by star count.
        - name: order
          in: query
          required: false
          schema:
            type: string
            enum: [asc, desc]
            default: desc
        - name: page
          in: query
          required: false
          schema:
            type: integer
            minimum: 1
            default: 1
        - name: per_page
          in: query
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 10
      responses:
        '200':
          description: Repository search results
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RepositorySearchResponse'

components:
  schemas:
    Repository:
      type: object
      additionalProperties: false
      properties:
        id:
          type: integer
        name:
          type: string
        full_name:
          type: string
        description:
          type: string
          nullable: true
        html_url:
          type: string
          format: uri
        stargazers_count:
          type: integer
        language:
          type: string
          nullable: true
      required:
        - id
        - name
        - full_name
        - html_url
        - stargazers_count
        - description
        - language

    RepositorySearchResponse:
      type: object
      properties:
        total_count:
          type: integer
        incomplete_results:
          type: boolean
        items:
          type: array
          items:
            $ref: '#/components/schemas/Repository'
      required:
        - total_count
        - incomplete_results
        - items
