/* tslint:disable */
/* eslint-disable */
/**
 * GitHub Search Repositories (Simplified)
 * Simplified schema for GitHub\'s /search/repositories endpoint. Only required fields for client display are included. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IRepository
 */
export interface IRepository {
    /**
     * 
     * @type {number}
     * @memberof IRepository
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof IRepository
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof IRepository
     */
    full_name: string;
    /**
     * 
     * @type {string}
     * @memberof IRepository
     */
    description: string | null;
    /**
     * 
     * @type {string}
     * @memberof IRepository
     */
    html_url: string;
    /**
     * 
     * @type {number}
     * @memberof IRepository
     */
    stargazers_count: number;
    /**
     * 
     * @type {string}
     * @memberof IRepository
     */
    language: string | null;
}

/**
 * Check if a given object implements the IRepository interface.
 */
export function instanceOfIRepository(value: object): value is IRepository {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('full_name' in value) || value['full_name'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('html_url' in value) || value['html_url'] === undefined) return false;
    if (!('stargazers_count' in value) || value['stargazers_count'] === undefined) return false;
    if (!('language' in value) || value['language'] === undefined) return false;
    return true;
}

export function IRepositoryFromJSON(json: any): IRepository {
    return IRepositoryFromJSONTyped(json, false);
}

export function IRepositoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): IRepository {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'full_name': json['full_name'],
        'description': json['description'],
        'html_url': json['html_url'],
        'stargazers_count': json['stargazers_count'],
        'language': json['language'],
    };
}

export function IRepositoryToJSON(json: any): IRepository {
    return IRepositoryToJSONTyped(json, false);
}

export function IRepositoryToJSONTyped(value?: IRepository | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'full_name': value['full_name'],
        'description': value['description'],
        'html_url': value['html_url'],
        'stargazers_count': value['stargazers_count'],
        'language': value['language'],
    };
}

